version: '3'
services:
  nginx:
    ports:
      - "80:80"

  nothy-server:
    build: 
      context: .
      args:
        NODE_ENV: production
    env_file:
      - ./production.env
    environment:
      - NODE_ENV=production
    command: node server.js